title = "Airspace for Hugo"
baseURL = "https://www.example.com"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "Work"
    url = "/work"
  [[menu.header]]
    weight = 3
    name = "Blog"
    url = "/blog"
  [[menu.header]]
    weight = 4
    name = "Contact"
    url = "/contact"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "The Krishnaswamy Lab at Yale University"
    subtitle = "We develop computational techniques to solve today’s challenging biological and medical problems."

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "Recent advances in single-cell technologies enable deep insights into cellular development, gene regulation, and phenotypic diversity by measuring gene expression and epigenetics for thousands of single cells in a single experiment. While these technologies hold great potential for improving our understanding of cellular states and progression, they also pose new challenges in terms of scale, complexity, noise and measurement artifact which require advanced mathematical and algorithmic tools to extract underlying biological signals."
    paragraph = "At the Krishnaswamy Lab, we work on one of the most promising techniques to tackle problems in single-cell technologies: manifold learning, and the related manifold assumption in data analysis. Manifold learning provides a powerful structure for algorithmic approaches to naturally process data, visualize it, understand progressions, find phenotypic diversity, and infer patterns. We have applied alternative approaches to manifold learning, diffusion-based and deep learning-based and showed results in several projects."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "Our work"
    content = "Click below to access the latest Krishnaswamy Lab Projects & Software."
    [params.feature.button]
      caption = "Explore lab projects"
      url = "#"

  [params.call]
    enable = true
    title = "Follow us on Twitter"
    [params.call.button]
      text = "@KrishnaswamyLab"
      url = "https://twitter.com/KrishnaswamyLab"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
